
-- MASTER FIX: Creates all tables and disables security blocks (RLS)
-- Run this in Supabase SQL Editor to fix "Not Saving" issues.

-- 1. Financial Records (Financeiro)
CREATE TABLE IF NOT EXISTS financial_records (
    id text PRIMARY KEY,
    customer_name text,
    description text,
    total numeric,
    status text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
ALTER TABLE financial_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON financial_records;
CREATE POLICY "Allow All" ON financial_records FOR ALL USING (true) WITH CHECK (true);

-- 2. Products (Meus Produtos)
CREATE TABLE IF NOT EXISTS products (
    id text PRIMARY KEY,
    name text,
    category text,
    price numeric,
    cost numeric,
    image text,
    description text,
    status text DEFAULT 'active',
    stock numeric,
    recipe jsonb, -- Stores the BOM (ingredients)
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON products;
CREATE POLICY "Allow All" ON products FOR ALL USING (true) WITH CHECK (true);

-- 3. Inventory Items (Insumos)
CREATE TABLE IF NOT EXISTS inventory_items (
    id text PRIMARY KEY,
    name text,
    supplier text,
    cost numeric,
    unit text,
    stock numeric DEFAULT 0,
    min_stock numeric DEFAULT 10,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON inventory_items;
CREATE POLICY "Allow All" ON inventory_items FOR ALL USING (true) WITH CHECK (true);

-- 4. Order Payments (Pagamentos)
CREATE TABLE IF NOT EXISTS order_payments (
    id bigint generated by default as identity primary key,
    order_id text,
    amount numeric,
    payment_method text, -- 'account' or 'cash'
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
ALTER TABLE order_payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON order_payments;
CREATE POLICY "Allow All" ON order_payments FOR ALL USING (true) WITH CHECK (true);

-- 5. Inventory Movements (Histórico de Estoque)
CREATE TABLE IF NOT EXISTS inventory_movements (
    id bigint generated by default as identity primary key,
    item_id text,
    type text, -- 'entrada', 'saida', 'perda'
    quantity numeric,
    reason text,
    user_email text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON inventory_movements;
CREATE POLICY "Allow All" ON inventory_movements FOR ALL USING (true) WITH CHECK (true);

-- 6. App Sync Logs (Logs do Botão Azul)
CREATE TABLE IF NOT EXISTS app_sync_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    page_context text,
    payload jsonb
);
ALTER TABLE app_sync_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON app_sync_logs;
CREATE POLICY "Allow All" ON app_sync_logs FOR ALL USING (true) WITH CHECK (true);
