-- MIGRATION: 001_create_protocol_system.sql
-- DESCRIÇÃO: Cria a estrutura para o sistema de Protocolos, Kanban e Flexibilidade Financeira.

-- 1. Tabela de Colunas do Kanban (O "Trello" configurável)
create table kanban_columns (
  id bigint generated by default as identity primary key,
  title text not null, -- Ex: 'Entrada', 'Arte', 'Produção'
  position integer not null, -- Ordem das colunas (1, 2, 3...)
  color text default '#e2e8f0', -- Cor visual da coluna
  is_locked boolean default false -- Se true, usuário não pode deletar
);

-- Insere as colunas padrão
insert into kanban_columns (title, position, color, is_locked) values
('Entrada (Lead)', 1, '#cbd5e1', true),
('Criação de Arte', 2, '#fef08a', false),
('Aguardando Pagamento', 3, '#fca5a5', false),
('Em Produção', 4, '#86efac', false),
('Expedição', 5, '#bae6fd', false),
('Concluído', 6, '#bbf7d0', true);


-- 2. Tabela de Protocolos (O "Coração" do sistema)
create table protocols (
  id text primary key, -- Identificador único #MV-XXXX
  client_id uuid references auth.users(id), -- Link com o cliente (se tiver conta)
  
  -- Controle de Fluxo
  column_id bigint references kanban_columns(id) default 1,
  
  -- Flexibilidade Financeira
  payment_status text default 'pending', -- 'pending', 'partial_50', 'paid_full'
  total_amount numeric(10,2) default 0.00,
  paid_amount numeric(10,2) default 0.00,
  
  -- Logística & Amostras
  delivery_address jsonb, -- Suporta múltiplos endereços em JSON
  requires_physical_sample boolean default false, -- Checkbox de Amostra Física
  
  -- Metadados
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  notes text -- Notas internas da equipe
);

-- 3. Itens do Protocolo (Produtos Flexíveis)
create table protocol_items (
  id bigint generated by default as identity primary key,
  protocol_id text references protocols(id) on delete cascade,
  
  product_name text not null, -- Nome gravado (caso produto mude depois)
  quantity integer not null,
  unit_price numeric(10,2) not null,
  total_price numeric(10,2) not null,
  
  customization_details jsonb -- Detalhes da personalização (Logo, Cor, etc)
);

-- 4. Função para Atualizar Preços (Atacado) na Tabela de Produtos Existente
-- Adicionamos uma coluna JSONB para a tabela de preços dinâmica
alter table products 
add column if not exists price_tiers jsonb default '[{"min": 1, "price": 0}]';

-- 5. Políticas de Segurança (RLS)
alter table protocols enable row level security;
alter table kanban_columns enable row level security;

-- O Admin vê tudo (ajuste conforme suas policies atuais)
create policy "Admin vê tudo" on protocols
for all using ( auth.role() = 'authenticated' ); -- Simplificado para dev

create policy "Admin edita colunas" on kanban_columns
for all using ( auth.role() = 'authenticated' );
