-- MIGRATION: 002_create_protocol_history.sql
-- DESCRIÇÃO: Implementa a tabela de auditoria (quem fez o quê) e funções seguras de movimentação.

-- 1. Tabela de Histórico (Auditoria)
-- Guarda cada movimento de card, pagamento ou aprovação.
create table protocol_history (
  id bigint generated by default as identity primary key,
  protocol_id text references protocols(id) on delete cascade,
  actor_id uuid references auth.users(id), -- Quem fez a ação (pode ser null se for sistema)
  action text not null, -- Ex: 'MOVED', 'PAID', 'APPROVED_ART', 'CREATED'
  details jsonb, -- Ex: { from: 'Entrada', to: 'Produção', reason: '...' }
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Segurança do Histórico (RLS)
alter table protocol_history enable row level security;

-- Política: Usuário vê histórico dos SEUS protocolos
create policy "Cliente vê seu histórico" on protocol_history
for select using (
  exists (
    select 1 from protocols p 
    where p.id = protocol_history.protocol_id 
    and p.client_id = auth.uid()
  )
);

-- Política: Admin vê tudo (Simplificado para authenticated por enquanto, ajuste conforme roles)
create policy "Admin vê tudo histórico" on protocol_history
for select using (
  auth.role() = 'authenticated'
);

-- Política: Ninguém edita ou deleta histórico (Imutável)
-- Não criamos policies de UPDATE/DELETE propositalmente.


-- 3. Função Segura: Mover Protocolo (Backend)
-- Essa função garante que ao mover um card, o histórico seja gravado AUTOMATICAMENTE.
create or replace function move_protocol(
  p_protocol_id text,
  p_new_column_id bigint,
  p_reason text default null
) returns void as $$
declare
  v_old_col bigint;
  v_actor uuid;
begin
  -- Identifica quem está chamando
  v_actor := auth.uid();
  
  -- Pega a coluna atual antes de mudar
  select column_id into v_old_col from protocols where id = p_protocol_id;

  -- Se não existir, erro
  if v_old_col is null then
    raise exception 'Protocolo não encontrado';
  end if;

  -- Atualiza o Protocolo
  update protocols 
  set column_id = p_new_column_id, 
      updated_at = now()
  where id = p_protocol_id;

  -- Grava no Histórico (O Dedo-duro)
  insert into protocol_history (protocol_id, actor_id, action, details)
  values (
    p_protocol_id, 
    v_actor, 
    'MOVED', 
    jsonb_build_object(
      'from_column', v_old_col, 
      'to_column', p_new_column_id,
      'reason', p_reason
    )
  );
end;
$$ language plpgsql security definer;
