-- MIGRATION: 003_setup_TOTAL_protocolos.sql
-- DESCRIÇÃO: Script "Tudo em Um" para garantir que o sistema B2B funcione 100%.
-- Segue ordem segura: Tabelas Base -> Colunas -> Histórico -> Funções e Polices.

-- =============================================================================
-- 1. ESTRUTURA BASE (Se já existir, não quebra)
-- =============================================================================

-- Tabela Pai: Protocolos
create table if not exists protocols (
    id text primary key, -- #MV-2026-XXXX
    client_id uuid references auth.users(id),
    column_id bigint default 1,
    total_amount numeric default 0.00,
    paid_amount numeric default 0.00,
    payment_status text default 'pending', -- pending, partial_50, paid_full
    notes text,
    requires_physical_sample boolean default false,
    art_approved boolean default false,
    art_approved_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabela Filha: Itens do Protocolo
create table if not exists protocol_items (
    id bigint generated by default as identity primary key,
    protocol_id text references protocols(id) on delete cascade,
    product_name text not null,
    quantity integer not null,
    unit_price numeric not null,
    total_price numeric not null,
    customization_details jsonb -- { cor: 'azul', logo: 'url...' }
);

-- Tabela Config: Colunas do Kanban
create table if not exists kanban_columns (
    id bigint generated by default as identity primary key,
    title text not null,
    position integer not null,
    color text default '#64748b'
);

-- =============================================================================
-- 2. DADOS INICIAIS (Seed)
-- =============================================================================

-- Cria as colunas padrão se estiver vazio
insert into kanban_columns (title, position, color)
select 'Entrada', 1, '#64748b'
where not exists (select 1 from kanban_columns where id = 1);

insert into kanban_columns (title, position, color)
select 'Aguardando Pagto', 2, '#eab308'
where not exists (select 1 from kanban_columns where id = 2);

insert into kanban_columns (title, position, color)
select 'Arte / Aprovação', 3, '#3b82f6'
where not exists (select 1 from kanban_columns where id = 3);

insert into kanban_columns (title, position, color)
select 'Em Produção', 4, '#f97316'
where not exists (select 1 from kanban_columns where id = 4);

insert into kanban_columns (title, position, color)
select 'Expedição/Entregue', 5, '#22c55e'
where not exists (select 1 from kanban_columns where id = 5);

-- =============================================================================
-- 3. INTELIGÊNCIA B2B (Módulo Novo)
-- =============================================================================

-- Tabela de Histórico (Auditoria)
create table if not exists protocol_history (
  id bigint generated by default as identity primary key,
  protocol_id text references protocols(id) on delete cascade,
  actor_id uuid references auth.users(id),
  action text not null,
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar RLS nas tabelas principais
alter table protocols enable row level security;
alter table protocol_items enable row level security;
alter table protocol_history enable row level security;

-- Política Protocols: Cliente vê seus, Admin vê tudo
create policy "Cliente vê seus protocolos" on protocols
for select using (auth.uid() = client_id);

create policy "Admin vê tudo protocolos" on protocols
for all using (auth.role() = 'authenticated'); -- Simplificado, ideal filtrar por role='admin' na tabela profiles

-- Política Histórico: Igual
create policy "Cliente vê seu histórico" on protocol_history
for select using (
  exists (
    select 1 from protocols p 
    where p.id = protocol_history.protocol_id 
    and p.client_id = auth.uid()
  )
);

create policy "Admin vê tudo histórico" on protocol_history
for select using (auth.role() = 'authenticated');


-- =============================================================================
-- 4. FUNÇÃO SEGURA 
-- =============================================================================

create or replace function move_protocol(
  p_protocol_id text,
  p_new_column_id bigint,
  p_reason text default null
) returns void as $$
declare
  v_old_col bigint;
  v_actor uuid;
begin
  v_actor := auth.uid();
  select column_id into v_old_col from protocols where id = p_protocol_id;

  if v_old_col is null then
    raise exception 'Protocolo não encontrado';
  end if;

  update protocols 
  set column_id = p_new_column_id, 
      updated_at = now()
  where id = p_protocol_id;

  insert into protocol_history (protocol_id, actor_id, action, details)
  values (
    p_protocol_id, 
    v_actor, 
    'MOVED', 
    jsonb_build_object('from', v_old_col, 'to', p_new_column_id, 'reason', p_reason)
  );
end;
$$ language plpgsql security definer;
