-- Non-destructive audit table for admin critical actions.
-- Safe to run multiple times.

create table if not exists public.admin_audit_logs (
    id bigint generated by default as identity primary key,
    actor_id uuid null,
    actor_email text null,
    actor_role text null,
    action text not null,
    entity_type text not null default 'protocol',
    entity_id text null,
    before_data jsonb null,
    after_data jsonb null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_admin_audit_logs_created_at
    on public.admin_audit_logs (created_at desc);

create index if not exists idx_admin_audit_logs_action
    on public.admin_audit_logs (action);

create index if not exists idx_admin_audit_logs_entity
    on public.admin_audit_logs (entity_type, entity_id);

alter table public.admin_audit_logs enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'admin_audit_logs'
          and policyname = 'admin_audit_logs_insert_authenticated'
    ) then
        create policy admin_audit_logs_insert_authenticated
            on public.admin_audit_logs
            for insert
            to authenticated
            with check (true);
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'admin_audit_logs'
          and policyname = 'admin_audit_logs_select_authenticated'
    ) then
        create policy admin_audit_logs_select_authenticated
            on public.admin_audit_logs
            for select
            to authenticated
            using (true);
    end if;
end $$;
