-- Create a table to store the sync logs from the blue button
create table if not exists app_sync_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  page_context text,
  payload jsonb
);

-- Policy to allow anonymous inserts (since we are simulating client-side auth/public access for now)
alter table app_sync_logs enable row level security;

create policy "Enable insert for all users" on app_sync_logs
  for insert with check (true);

create policy "Enable read for all users" on app_sync_logs
  for select using (true);
